# Generated by Django 4.2.3 on 2023-07-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='lastname',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
