# Generated by Django 4.2.3 on 2023-07-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_firstname_accountdetail_fullname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetail',
        ),
    ]
